### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Noctophile** [Dhruv-Tara/Auto-Anime-Bot#2]
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/root/aab/AAB/__init__.py", line 23
    LOG.info(f"Licensed Under : {Vars["Licensed_under"]}")
                                       ^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by Noctophile** [comment]
Upper one is solved .but what to do in this ??

![Screenshot_20241006-002744_exteraGram](https://github.com/user-attachments/assets/65ec3a98-8be8-4a99-af30-ccd3d42bbd5e)

**Comment by Dhruv-Tara** [comment]
might be some issue with mongo, check your mongo server.
